server 
{

	listen	80;

	server_name api.wh40kcards.ru;
	resolver 8.8.8.8;


	location / 
	{
		root   /usr/share/nginx/html;
		index  index.html index.htm;
		try_files $uri $uri/ /index.html;
	}


	location /api 
	{
		proxy_pass http://back40api:8080;
	}
	location /scalar 
	{
		proxy_pass http://back40api:8080;
	}
	location /openapi 
	{
		proxy_pass http://back40api:8080;
	}


}